Plugin adds a speedmap layer
SW8-Mobility/hast_qgis_plugin pull request #13
Opened 2023-04-24 18:05 UTC by JakobFaarGreg

2023-04-24 20:38 UTC, JakobFaarGreg reviewed
looks good to me

2023-04-25 06:41 UTC, CasperKjaerhus approved these changes

2023-04-25 06:41 UTC, CasperKjaerhus commented
lgtm

2023-04-25 06:43 UTC, frejaz commented on hast_qgis_plugin_dockwidget.py
> +    def insert_spedmap_layer(self):
Mangler docstrings <3

2023-04-25 06:44 UTC, frejaz commented on hast_qgis_plugin_dockwidget.py
> +        self.calculateSpeedLimitButton.clicked.connect(self.insert_spedmap_layer)
Du må gerne lave en kommentar ift. hvad der sker her

2023-04-25 06:44 UTC, frejaz requested changes
B)

2023-04-25 06:50 UTC, frejaz commented on hast_qgis_plugin_dockwidget.py
> +                "/Users/lille/Speedmap/hastighedsgraenser2008-01-21.shp",
Måske en #TODO på den her?

2023-04-25 06:59 UTC, JakobFaarGreg commented on hast_qgis_plugin_dockwidget.py
> +                "/Users/lille/Speedmap/hastighedsgraenser2008-01-21.shp",
Jeg har en føler ud til Tanja om jeg må lægge speedmap dataen op på Github

2023-04-28 12:22 UTC, frejaz approved these changes
nice

2023-04-28 12:22 UTC, merged